### ISSUE TITLE
UserStories

### ISSUE THREAD

**Issue by 7thDecember** [SoftwareEngineering-Course-Group/UF-OpenMart#4]
As a customer:
I want to find a market that list all the used items with fair price.
so that an online second-hand market needed to be built.
As a seller:
I want to find a market that can sell my used items to get some cash back.
so that an online second-hand market needed to be built.
As a businessman:
I want to spend less time finding a market that can compare used item together to find the most proper one for me.
so that a market needs to categorize the items by tags or attribute.
As a student:
I want to find a market that can compares used item together to find the cheapest one for me.
so that a market needs to mark all the items' price and rearrange the order of item with specific requirements.
As a seller/customer who wants to protect his/her privacy:
I want to find an online market that require less personal information.
so that the market needs to reduce personal information collection and focus on making connection between the sellers and customers.
As a crypto lover(optional):
I want to find an online market that can use Crypto coin to make the payment.
so that the market needs to connect to WEB3 wallet.

**Comment by Yuyangbo** [comment]
Nice work!
